name: Java CI

on: [push]

jobs:
  buildJar:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-level: 33
          build-tools: 33.0.2
          target: default

      - name: Install Android SDK Platform 33
        run: |
          sdkmanager "platforms;android-33" "build-tools;33.0.2"

      - name: Check Android SDK Installation
        run: ls -la $ANDROID_SDK_ROOT/platforms/android-33

      - name: Build and dexify mod jar file
        run: |
          chmod +x gradlew
          ./gradlew main:deploy main:dex tools:proc --info

      - name: Upload built mod jar file
        uses: actions/upload-artifact@v4
        with:
          name: ProjectUnity (zipped)
          path: main/build/libs/ProjectUnity.jar